services:
  asrp_database:
    container_name: asrp_database
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./compose/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U ${DB_USER:-test}"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default

  asrp_backend:
    container_name: asrp_backend
    build:
      context: .
      dockerfile: compose/backend/Dockerfile
    depends_on:
      asrp_database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./app/:/app/app/
      - ./alembic/:/app/alembic
      - ./logs/:/app/logs
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - asrp_backend
    restart: unless-stopped
    networks:
      - default

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    restart: "no"
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email admin@asrpath.org --agree-tos --no-eff-email -d asrpath.org
    networks:
      - default


volumes:
  postgres_data:
  etc-letsencrypt:
  www-html:


networks:
  default:
    driver: bridge
