"""added message type enum

Revision ID: 004
Revises: 003
Create Date: 2026-01-19 01:06:56.543173

"""

from typing import Sequence, Union

import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # При создании Enum'а в уже существующей таблице, его надо создавать отдельно
    contact_message_type_enum = postgresql.ENUM(
        "CONTACT", "GET_INVOLVED", "GET_INVOLVED_COMMITTEES", name="contact_message_type_enum"
    )
    contact_message_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "contact_messages",
        sa.Column(
            "type",
            contact_message_type_enum,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact_messages", "type")
    op.execute("DROP TYPE IF EXISTS contact_message_type_enum")
    # ### end Alembic commands ###
