"""feedback permissions

Revision ID: 006
Revises: 005
Create Date: 2026-01-26 11:33:38.427461

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "006"
down_revision: Union[str, None] = "005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = sa.table(
        "permissions", sa.column("action", sa.String), sa.column("name", sa.String), sa.Column("_deleted", sa.Boolean)
    )

    op.bulk_insert(
        permissions_table,
        [
            {"action": "feedback.create", "name": "Assign admin feedback"},
            {"action": "feedback.view", "name": "View admin feedback"},
            {"action": "feedback.delete", "name": "Remove admin feedback"},
            {"action": "feedback.update", "name": "Update admin feedback"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            DELETE FROM permissions WHERE action IN (
            'feedback.create',
            'feedback.view',
            'feedback.delete',
            'feedback.update'
            )
        """)
    )
    # ### end Alembic commands ###
