"""legal_documents permissions

Revision ID: 007
Revises: 006
Create Date: 2026-02-04 13:02:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "007"
down_revision: Union[str, None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = sa.table(
        "permissions",
        sa.column("action", sa.String),
        sa.column("name", sa.String),
        sa.column("_deleted", sa.Boolean)
    )

    op.bulk_insert(
        permissions_table,
        [
            {"action": "legal_documents.create", "name": "Create legal documents"},
            {"action": "legal_documents.view", "name": "View legal documents"},
            {"action": "legal_documents.update", "name": "Update legal documents"},
            {"action": "legal_documents.delete", "name": "Delete legal documents"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            DELETE FROM permissions WHERE action IN (
            'legal_documents.create',
            'legal_documents.view',
            'legal_documents.update',
            'legal_documents.delete'
            )
        """)
    )
    # ### end Alembic commands ###
