"""empty message

Revision ID: 007_add_user_profile_fields
Revises: 006
Create Date: 2026-02-02 15:49:59.723385

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '007_add_user_profile_fields'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middlename', sa.String(), nullable=True))
    op.add_column('users', sa.Column('suffix', sa.String(), nullable=True))
    op.add_column('users', sa.Column('credentials', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('users', sa.Column('languages_spoken', sa.String(), nullable=True))
    op.add_column('users', sa.Column('professional_interests', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_telegram_username'), 'users', ['telegram_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_telegram_username'), 'users', type_='unique')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'professional_interests')
    op.drop_column('users', 'languages_spoken')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state')
    op.drop_column('users', 'country')
    op.drop_column('users', 'credentials')
    op.drop_column('users', 'suffix')
    op.drop_column('users', 'middlename')
    # ### end Alembic commands ###
