"""user communication_preferences

Revision ID: 046b3ddb4455
Revises: ffff45a3f270
Create Date: 2026-03-22 13:27:09.349607

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "046b3ddb4455"
down_revision: Union[str, None] = "ffff45a3f270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_communication_preferences",
        sa.Column("membership_account_notifications", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("newsletters", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("events_meetings", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("committees_leadership", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("volunteer_opportunities", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_users_communication_preferences_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_communication_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_communication_preferences_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_communication_preferences")
    # ### end Alembic commands ###
