"""one successful membership application per request

Revision ID: 04c788d04f52
Revises: fac5c394e2c1
Create Date: 2026-05-04 21:25:28.941668

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04c788d04f52"
down_revision: Union[str, None] = "fac5c394e2c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("membership_request_id", sa.Integer(), nullable=True))
    op.create_index(
        "uq_payments_one_membership_application_per_membership_request",
        "payments",
        ["membership_request_id"],
        unique=True,
        postgresql_where=sa.text(
            "purpose = 'MEMBERSHIP_APPLICATION' AND membership_request_id IS NOT NULL AND status = 'SUCCEEDED'"
        ),
    )
    op.create_foreign_key(
        op.f("fk_payments_membership_request_id_membership_requests"),
        "payments",
        "membership_requests",
        ["membership_request_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_payments_membership_request_id_membership_requests"), "payments", type_="foreignkey")
    op.drop_index(
        "uq_payments_one_membership_application_per_membership_request",
        table_name="payments",
        postgresql_where=sa.text(
            "purpose = 'MEMBERSHIP_APPLICATION' AND membership_request_id IS NOT NULL AND status = 'SUCCEEDED'"
        ),
    )
    op.drop_column("payments", "membership_request_id")
    # ### end Alembic commands ###
