"""insert initial data

Revision ID: 09835558b39e
Revises: 4f420931157f
Create Date: 2026-04-18 01:06:20.540984

"""

from typing import Sequence, Union

import sqlalchemy as sa

# revision identifiers, used by Alembic.
from passlib.handlers.bcrypt import bcrypt

from alembic import op
from app.core.config import DEV_MODE

revision: str = "09835558b39e"
down_revision: Union[str, None] = "4f420931157f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    metadata = sa.MetaData()
    bind = op.get_bind()

    permissions_table = sa.Table(
        "permissions",
        metadata,
        autoload_with=bind,
    )
    users_table = sa.Table(
        "users",
        metadata,
        autoload_with=bind,
    )
    membership_types_table = sa.Table(
        "membership_types",
        metadata,
        autoload_with=bind,
    )

    op.bulk_insert(
        permissions_table,
        [
            # Admin managing permissions
            {"action": "admin.create", "name": "Assign admin role"},
            {"action": "admin.view", "name": "View admin profile"},
            {"action": "admin.delete", "name": "Remove admin role"},
            {"action": "admin.update", "name": "Update admin profile"},
            # Permissions managing permissions
            {"action": "permissions.create", "name": "Create permissions"},
            {"action": "permissions.view", "name": "View permissions"},
            {"action": "permissions.delete", "name": "Delete permissions"},
            {"action": "permissions.update", "name": "Update permissions"},
            # Membership managing permissions
            {"action": "memberships.create", "name": "Create memberships"},
            {"action": "memberships.view", "name": "View memberships"},
            {"action": "memberships.delete", "name": "Delete memberships"},
            {"action": "memberships.update", "name": "Update memberships"},
            # Feedback managing permissions
            {"action": "feedback.create", "name": "Assign admin feedback"},
            {"action": "feedback.view", "name": "View admin feedback"},
            {"action": "feedback.delete", "name": "Remove admin feedback"},
            {"action": "feedback.update", "name": "Update admin feedback"},
            {"action": "directors_board.create", "name": "Create director board members"},
            {"action": "directors_board.view", "name": "View director board members"},
            {"action": "directors_board.delete", "name": "Remove director board members"},
            {"action": "directors_board.update", "name": "Update director board members"},
            {"action": "legal_documents.create", "name": "Create legal documents"},
            {"action": "legal_documents.view", "name": "View legal documents"},
            {"action": "legal_documents.update", "name": "Update legal documents"},
            {"action": "legal_documents.delete", "name": "Delete legal documents"},
            {"action": "name_change_requests.view", "name": "View name change requests"},
            {"action": "name_change_requests.update", "name": "Approve/reject name change request"},
            {"action": "name_change_requests.create", "name": "Create name change request"},
            {"action": "name_change_requests.delete", "name": "Delete name change request"},
        ],
    )

    op.bulk_insert(
        membership_types_table,
        [
            {
                "name": "Active Member",
                "type": "ACTIVE",
                "price_usd": 120.00,
                "duration": 365,
                "description": "Any legally qualified Russian-speaking specialist (MD, DO, MBBS, PhD, or equivalent degree). practicing pathology in the united states",
                "is_purchasable": True,
            },
            {
                "name": "Trainee Member",
                "type": "TRAINEE",
                "price_usd": 60.00,
                "duration": 365,
                "description": "Russian-speaking residents or fellows in pathology or related disciplines in the United States.",
                "is_purchasable": True,
            },
            {
                "name": "Affiliate Member",
                "type": "AFFILIATE",
                "price_usd": 90.00,
                "duration": 365,
                "description": "Russian-speaking pathologists, scientists, researchers, or allied professionals interested in the field of pathology whose involvement is relevant and contributes meaningfully to the Society (non-voting).",
                "is_purchasable": True,
            },
            {
                "name": "Honorary Member",
                "type": "HONORARY",
                "price_usd": 0.00,
                "duration": 365,
                "description": "Individuals recognized fo exceptional service to the field of pathology or the Society (non-voting).",
                "is_purchasable": False,
            },
            {
                "name": "Pathway Member",
                "type": "PATHWAY",
                "price_usd": 30.00,
                "duration": 365,
                "description": "Russian-speaking individuals pursuing or transition into a medical career in the United States. This includes medical students and internationally trained medical graduates seeking mentorship and professional development as they prepare for pathology practice in the United States (non-voting).",
                "is_purchasable": True,
            },
        ],
    )

    if DEV_MODE:
        hashed_password = bcrypt.hash("admin")
        op.bulk_insert(
            users_table,
            [
                {
                    "firstname": "Admin",
                    "lastname": "User",
                    "email": "admin@mail.com",
                    "admin": True,
                    "description": "Development superuser",
                    "country": "USA",
                    "city": "New York",
                    "_password": hashed_password,
                    "pending": False,
                }
            ],
        )

        op.execute("INSERT INTO users_permissions (permission_id, user_id) SELECT permissions.id, 1 FROM permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM membership_requests
        WHERE membership_type_id IN (
            SELECT id
            FROM membership_types
            WHERE type IN ('ACTIVE', 'TRAINEE', 'AFFILIATE', 'HONORARY', 'PATHWAY')
        )
    """)

    op.execute("""
        DELETE FROM membership_types
        WHERE type IN ('ACTIVE', 'TRAINEE', 'AFFILIATE', 'HONORARY', 'PATHWAY')
    """)

    op.execute("""
        DELETE FROM users_permissions WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
    """)

    op.execute("""
        DELETE FROM permissions
        WHERE action IN (
            'admin.create',
            'admin.view',
            'admin.delete',
            'admin.update',
            'permissions.create',
            'permissions.view',
            'permissions.delete',
            'permissions.update',
            'memberships.create',
            'memberships.view',
            'memberships.delete',
            'memberships.update',
            'feedback.create',
            'feedback.view',
            'feedback.delete',
            'feedback.update',
            'directors_board.create',
            'directors_board.view',
            'directors_board.delete',
            'directors_board.update',
            'legal_documents.create',
            'legal_documents.view',
            'legal_documents.update',
            'legal_documents.delete',
            'name_change_requests.view',
            'name_change_requests.update',
            'name_change_requests.create',
            'name_change_requests.delete'
        )
    """)
    if DEV_MODE:
        op.execute("""
            DELETE FROM feedback_additional_info
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM membership_requests
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM name_change_requests
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM news
            WHERE author_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM payments
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM users_communication_preferences
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM users_fellowships
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM users_jobs
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute(
            "DELETE FROM users_permissions WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')"
        )
        op.execute("""
            DELETE FROM users_professional_information
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("""
            DELETE FROM users_residencies
            WHERE user_id = (SELECT id FROM users WHERE email = 'admin@mail.com')
        """)
        op.execute("DELETE FROM users WHERE email = 'admin@mail.com'")
    # ### end Alembic commands ###
