"""edit communication preferences table

Revision ID: 136c85a1fc49
Revises: 0f7e4c431a00
Create Date: 2026-03-16 23:15:29.216062

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '136c85a1fc49'
down_revision: Union[str, None] = '0f7e4c431a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
