"""membership suspension termination

Revision ID: 15b185145d89
Revises: c85804cc0c22
Create Date: 2026-05-31 21:26:32.096080

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15b185145d89"
down_revision: Union[str, None] = "c85804cc0c22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_memberships", sa.Column("terminated", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("users_memberships", sa.Column("termination_reason", sa.String(), nullable=True))
    op.add_column("users_memberships", sa.Column("terminated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users_memberships", sa.Column("suspended_until", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users_memberships", sa.Column("suspension_reason", sa.String(), nullable=True))
    op.add_column("users_memberships", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_memberships", "suspended_at")
    op.drop_column("users_memberships", "suspension_reason")
    op.drop_column("users_memberships", "suspended_until")
    op.drop_column("users_memberships", "terminated_at")
    op.drop_column("users_memberships", "termination_reason")
    op.drop_column("users_memberships", "terminated")
    # ### end Alembic commands ###
