"""case of the month

Revision ID: 189aadef19d8
Revises: d5e8f31a4b72
Create Date: 2026-09-27 21:21:16.561510

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "189aadef19d8"
down_revision: Union[str, None] = "d5e8f31a4b72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_tags",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_tags")),
    )
    op.create_index(op.f("ix_case_tags_name"), "case_tags", ["name"], unique=True)
    op.create_table(
        "cases_of_the_month",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("case_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("publication_month", sa.Date(), nullable=False),
        sa.Column("questions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases_of_the_month")),
    )
    op.create_index(op.f("ix_cases_of_the_month_slug"), "cases_of_the_month", ["slug"], unique=True)
    op.create_table(
        "cases_of_the_month_tags",
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases_of_the_month.id"], name=op.f("fk_cases_of_the_month_tags_case_id_cases_of_the_month")
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["case_tags.id"], name=op.f("fk_cases_of_the_month_tags_tag_id_case_tags")),
        sa.PrimaryKeyConstraint("case_id", "tag_id", name=op.f("pk_cases_of_the_month_tags")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cases_of_the_month_tags")
    op.drop_index(op.f("ix_cases_of_the_month_slug"), table_name="cases_of_the_month")
    op.drop_table("cases_of_the_month")
    op.drop_index(op.f("ix_case_tags_name"), table_name="case_tags")
    op.drop_table("case_tags")
    # ### end Alembic commands ###
