"""middlename_in_name_change_requests

Revision ID: 1901826ca4d1
Revises: 207ea20e433d
Create Date: 2026-03-12 21:37:08.639676

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1901826ca4d1"
down_revision: Union[str, None] = "207ea20e433d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("name_change_requests", sa.Column("middlename", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("name_change_requests", "middlename")
    # ### end Alembic commands ###
