"""json field instead nullable fields

Revision ID: 005
Revises: 004
Create Date: 2026-01-25 19:42:25.658342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "21becd3cff73"
down_revision = "073806ce77bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_messages", sa.Column("message_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    )
    op.drop_column("contact_messages", "subject")
    op.drop_column("contact_messages", "get_involved_message")
    op.drop_column("contact_messages", "contact_message")
    op.drop_column("contact_messages", "role_affiliation")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_messages", sa.Column("role_affiliation", sa.VARCHAR(length=256), autoincrement=False, nullable=True)
    )
    op.add_column("contact_messages", sa.Column("contact_message", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("contact_messages", sa.Column("get_involved_message", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("contact_messages", sa.Column("subject", sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column("contact_messages", "message_content")
    # ### end Alembic commands ###
