"""membership downgrade requests

Revision ID: 2d66df0d3c74
Revises: 6e29a6badfb9
Create Date: 2026-05-28 12:45:06.848754

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d66df0d3c74"
down_revision: Union[str, None] = "6e29a6badfb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUM_NAME = "payment_purpose_enum"
NEW_VALUE = "MEMBERSHIP_TYPE_UPGRADE"

OLD_VALUES = (
    "MEMBERSHIP_APPLICATION",
    "MEMBERSHIP_RENEWAL",
    "DONATION",
)

PAYMENT_PURPOSE_INDEX_NAME = "uq_payments_one_membership_application_per_membership_request"
PAYMENT_PURPOSE_INDEX_WHERE = (
    "purpose = 'MEMBERSHIP_APPLICATION' AND membership_request_id IS NOT NULL AND status = 'SUCCEEDED'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership_downgrade_requests",
        sa.Column("target_membership_type_id", sa.Integer(), nullable=False),
        sa.Column("user_membership_id", sa.Integer(), nullable=False),
        sa.Column("reason_changing", sa.String(length=512), nullable=False),
        sa.Column("approved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("admin_comment", sa.String(), nullable=True),
        sa.Column("pending", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "pending = TRUE OR approved = TRUE OR admin_comment IS NOT NULL",
            name=op.f("ck_membership_downgrade_requests_membership_type_change_request_rejection_comment"),
        ),
        sa.ForeignKeyConstraint(
            ["target_membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_membership_downgrade_requests_target_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(
            ["user_membership_id"],
            ["users_memberships.id"],
            name=op.f("fk_membership_downgrade_requests_user_membership_id_users_memberships"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_downgrade_requests")),
    )
    op.create_index(
        "unique_pending_membership_type_change_request_per_membership",
        "membership_downgrade_requests",
        ["user_membership_id"],
        unique=True,
        postgresql_where=sa.text("pending = true AND _deleted = false"),
    )

    op.execute(
        f"""
        ALTER TYPE {ENUM_NAME}
        ADD VALUE '{NEW_VALUE}'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_pending_membership_type_change_request_per_membership",
        table_name="membership_downgrade_requests",
        postgresql_where=sa.text("pending = true AND _deleted = false"),
    )
    op.drop_table("membership_downgrade_requests")

    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM payments
                WHERE purpose = '{NEW_VALUE}'
            ) THEN
                RAISE EXCEPTION
                    'Cannot downgrade: enum value {NEW_VALUE} is still used';
            END IF;
        END$$;
        """
    )

    old_values_sql = ", ".join(f"'{v}'" for v in OLD_VALUES)

    op.drop_index(
        PAYMENT_PURPOSE_INDEX_NAME,
        table_name="payments",
        postgresql_where=sa.text(PAYMENT_PURPOSE_INDEX_WHERE),
    )

    op.execute(
        f"""
        CREATE TYPE {ENUM_NAME}_old AS ENUM (
            {old_values_sql}
        )
        """
    )

    op.execute(
        f"""
        ALTER TABLE payments
        ALTER COLUMN purpose
        TYPE {ENUM_NAME}_old
        USING purpose::text::{ENUM_NAME}_old
        """
    )

    op.execute(f"DROP TYPE {ENUM_NAME}")

    op.execute(
        f"""
        ALTER TYPE {ENUM_NAME}_old
        RENAME TO {ENUM_NAME}
        """
    )

    op.create_index(
        PAYMENT_PURPOSE_INDEX_NAME,
        "payments",
        ["membership_request_id"],
        unique=True,
        postgresql_where=sa.text(PAYMENT_PURPOSE_INDEX_WHERE),
    )
    # ### end Alembic commands ###
