"""director board

Revision ID: 001
Revises: 000
Create Date: 2025-12-26 21:00:05.331992

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f846565bf54"
down_revision = "d9064d4df926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "director_board_members",
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_director_board_members")),
    )
    # ### end Alembic commands ###
    metadata = sa.MetaData()
    bind = op.get_bind()

    permissions_table = sa.Table(
        "permissions",
        metadata,
        autoload_with=bind,
    )

    op.bulk_insert(
        permissions_table,
        [
            {"action": "director_board.create", "name": "Create director board members"},
            {"action": "director_board.view", "name": "View director board members"},
            {"action": "director_board.delete", "name": "Remove director board members"},
            {"action": "director_board.update", "name": "Update director board members"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("director_board_members")
    op.execute(
        sa.text("""
            DELETE FROM permissions
            WHERE action IN (
                'director_board.create',
                'director_board.view',
                'director_board.delete',
                'director_board.update'
            )
        """)
    )
    # ### end Alembic commands ###
