"""add_banned_and_ban_reason_to_user

Revision ID: 31057bd009bb
Revises: c85804cc0c22
Create Date: 2026-06-03 13:19:03.372185

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31057bd009bb"
down_revision: Union[str, None] = "c85804cc0c22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("banned", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("users", sa.Column("ban_reason", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "ban_reason")
    op.drop_column("users", "banned")
    # ### end Alembic commands ###
