"""user_membership_type_change_requests

Revision ID: 467a97090f43
Revises: 6e29a6badfb9
Create Date: 2026-05-21 18:10:58.730958

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "467a97090f43"
down_revision: Union[str, None] = "6e29a6badfb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_membership_type_change_requests",
        sa.Column("target_membership_type_id", sa.Integer(), nullable=False),
        sa.Column("user_membership_id", sa.Integer(), nullable=False),
        sa.Column("upgrade", sa.Boolean(), nullable=False),
        sa.Column("reason_changing", sa.String(length=512), nullable=False),
        sa.Column("approved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("admin_comment", sa.String(), nullable=True),
        sa.Column("pending", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "pending = TRUE OR approved = TRUE OR admin_comment IS NOT NULL",
            name=op.f("ck_user_membership_type_change_requests_membership_type_change_request_rejection_comment"),
        ),
        sa.ForeignKeyConstraint(
            ["target_membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_user_membership_type_change_requests_target_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(
            ["user_membership_id"],
            ["users_memberships.id"],
            name=op.f("fk_user_membership_type_change_requests_user_membership_id_users_memberships"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_membership_type_change_requests")),
    )
    op.create_index(
        "unique_pending_membership_type_change_request_per_membership",
        "user_membership_type_change_requests",
        ["user_membership_id"],
        unique=True,
        postgresql_where=sa.text("pending = true AND _deleted = false"),
    )
    # ### end Alembic commands ###

    op.execute("ALTER TYPE payment_purpose_enum ADD VALUE IF NOT EXISTS 'MEMBERSHIP_TYPE_UPGRADE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_pending_membership_type_change_request_per_membership",
        table_name="user_membership_type_change_requests",
        postgresql_where=sa.text("pending = true AND _deleted = false"),
    )
    op.drop_table("user_membership_type_change_requests")
    # ### end Alembic commands ###

    # TODO: MEMBERSHIP_TYPE_UPGRADE deletion
