"""cases new fields

Revision ID: 4d0f674b8e59
Revises: 189aadef19d8
Create Date: 2026-09-28 18:36:01.526315

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4d0f674b8e59"
down_revision: Union[str, None] = "189aadef19d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases_of_the_month", sa.Column("cover_key", sa.String(), nullable=True))
    op.add_column(
        "cases_of_the_month",
        sa.Column(
            "virtual_slides",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
    )
    op.alter_column("cases_of_the_month", "virtual_slides", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases_of_the_month", "virtual_slides")
    op.drop_column("cases_of_the_month", "cover_key")
    # ### end Alembic commands ###
