"""Initial

Revision ID: 4f420931157f
Revises:
Create Date: 2026-04-18 01:03:19.727384

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f420931157f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_messages",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CONTACT", "GET_INVOLVED", "GET_INVOLVED_COMMITTEES", name="contact_message_type_enum"),
            nullable=False,
        ),
        sa.Column("answered", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("message_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages")),
    )
    op.create_table(
        "directors_board_members",
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directors_board_members")),
        sa.UniqueConstraint("order", name=op.f("uq_directors_board_members_order")),
    )
    op.create_table(
        "membership_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ACTIVE", "TRAINEE", "AFFILIATE", "HONORARY", "PATHWAY", name="membership_type_enum"),
            nullable=False,
        ),
        sa.Column("price_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_purchasable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_types")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_table(
        "processed_webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processed_webhook_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_processed_webhook_events_event_id")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("middlename", sa.String(), nullable=True),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("preferred_name", sa.String(), nullable=True),
        sa.Column("suffix", sa.String(), nullable=True),
        sa.Column("credentials", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("languages_spoken", sa.String(), nullable=True),
        sa.Column("professional_interests", sa.String(), nullable=True),
        sa.Column("telegram_username", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("pending", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("last_password_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_name_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("_password", sa.String(), nullable=False),
        sa.Column("avatar_path", sa.String(), nullable=True),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("avatar_path", name=op.f("uq_users_avatar_path")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_users_phone_number")),
        sa.UniqueConstraint("telegram_username", name=op.f("uq_users_telegram_username")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "contact_messages_replies",
        sa.Column("contact_message_id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_message_id"],
            ["contact_messages.id"],
            name=op.f("fk_contact_messages_replies_contact_message_id_contact_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages_replies")),
    )
    op.create_table(
        "feedback_additional_info",
        sa.Column("hear_about_asrp", sa.String(), nullable=False),
        sa.Column("tg_username", sa.String(), nullable=True),
        sa.Column("interest_description", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_feedback_additional_info_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_additional_info")),
        sa.UniqueConstraint("user_id", name=op.f("uq_feedback_additional_info_user_id")),
    )
    op.create_table(
        "membership_requests",
        sa.Column(
            "status",
            sa.Enum(
                "PAYMENT_PENDING",
                "PAID",
                "APPROVED",
                "REJECTED",
                "PAYMENT_FAILED",
                name="membership_request_status_enum",
            ),
            server_default=sa.text("'PAYMENT_PENDING'"),
            nullable=False,
        ),
        sa.Column("primary_affiliation", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.Column("practice_setting", sa.String(), nullable=False),
        sa.Column("subspecialty", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_comment", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("membership_type_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_membership_requests_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_membership_requests_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_requests")),
        sa.UniqueConstraint("user_id", name=op.f("uq_membership_requests_user_id")),
    )
    op.create_table(
        "name_change_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("middlename", sa.String(), nullable=True),
        sa.Column("reason_change", sa.String(), nullable=False),
        sa.Column("reason_rejecting", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="name_change_request_status_enum"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_name_change_requests_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_name_change_requests")),
    )
    op.create_table(
        "news",
        sa.Column("body", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_news_author_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news")),
    )
    op.create_table(
        "payments",
        sa.Column("provider", sa.Enum("STRIPE", name="payment_provider_enum"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCEEDED", "FAILED", "CANCELED", "EXPIRED", "REFUNDED", name="payment_status_enum"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "purpose",
            sa.Enum("MEMBERSHIP_APPLICATION", "MEMBERSHIP_RENEWAL", "DONATION", name="payment_purpose_enum"),
            nullable=False,
        ),
        sa.Column("provider_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_table(
        "users_communication_preferences",
        sa.Column("membership_account_notifications", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("newsletters", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("events_meetings", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("committees_leadership", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("volunteer_opportunities", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_users_communication_preferences_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_communication_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_communication_preferences_user_id")),
    )
    op.create_table(
        "users_fellowships",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("current_position", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("speciality", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_fellowships_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_fellowships")),
    )
    op.create_table(
        "users_jobs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("current_position", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("speciality", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_jobs_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_jobs")),
    )
    op.create_table(
        "users_permissions",
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], name=op.f("fk_users_permissions_permission_id_permissions")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_permissions_user_id_users")),
        sa.PrimaryKeyConstraint("permission_id", "user_id", name=op.f("pk_users_permissions")),
    )
    op.create_table(
        "users_professional_information",
        sa.Column("medical_school", sa.String(), nullable=False),
        sa.Column("medical_school_country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.Column("is_board_certified_pathologist", sa.Boolean(), nullable=False),
        sa.Column("is_us_pathology_trainee", sa.Boolean(), nullable=False),
        sa.Column("is_us_lab_professional", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_users_professional_information_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_professional_information")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_professional_information_user_id")),
    )
    op.create_table(
        "users_residencies",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("current_position", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("speciality", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_residencies_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_residencies")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_residencies")
    op.drop_table("users_professional_information")
    op.drop_table("users_permissions")
    op.drop_table("users_jobs")
    op.drop_table("users_fellowships")
    op.drop_table("users_communication_preferences")
    op.drop_table("payments")
    op.drop_table("news")
    op.drop_table("name_change_requests")
    op.drop_table("membership_requests")
    op.drop_table("feedback_additional_info")
    op.drop_table("contact_messages_replies")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("processed_webhook_events")
    op.drop_table("permissions")
    op.drop_table("membership_types")
    op.drop_table("directors_board_members")
    op.drop_table("contact_messages")
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS payment_provider_enum")
    op.execute("DROP TYPE IF EXISTS payment_status_enum")
    op.execute("DROP TYPE IF EXISTS payment_purpose_enum")
    op.execute("DROP TYPE IF EXISTS approval_status_enum")
    op.execute("DROP TYPE IF EXISTS membership_type_enum")
    op.execute("DROP TYPE IF EXISTS contact_message_type_enum")
    op.execute("DROP TYPE IF EXISTS membership_request_status_enum")
    op.execute("DROP TYPE IF EXISTS name_change_request_status_enum")
