"""membership request reviewer id

Revision ID: 4f7c67fabbd9
Revises: 09835558b39e
Create Date: 2026-04-27 21:59:03.076759

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4f7c67fabbd9"
down_revision: Union[str, None] = "09835558b39e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("membership_requests", sa.Column("reviewer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_membership_requests_reviewer_id_users"), "membership_requests", "users", ["reviewer_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_membership_requests_reviewer_id_users"), "membership_requests", type_="foreignkey")
    op.drop_column("membership_requests", "reviewer_id")
    # ### end Alembic commands ###
