"""payments

Revision ID: 50ef4536f557
Revises: f9a34e2d51c1
Create Date: 2026-04-04 16:11:52.218496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50ef4536f557"
down_revision: Union[str, None] = "f9a34e2d51c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("provider", sa.Enum("STRIPE", name="payment_provider_enum"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("currency", sa.String(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCEEDED", "FAILED", "CANCELED", "EXPIRED", "REFUNDED", name="payment_status_enum"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "purpose",
            sa.Enum("MEMBERSHIP_APPLICATION", "MEMBERSHIP_RENEWAL", "DONATION", name="payment_purpose_enum"),
            nullable=False,
        ),
        sa.Column("provider_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS payment_provider_enum")
    op.execute("DROP TYPE IF EXISTS payment_status_enum")
    op.execute("DROP TYPE IF EXISTS payment_purpose_enum")
