"""archived language timezone webinars

Revision ID: 5ed5e36adc73
Revises: a91f0b62d183
Create Date: 2026-08-14 18:18:02.493760

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5ed5e36adc73"
down_revision: Union[str, None] = "a91f0b62d183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webinars", sa.Column("timezone", sa.String(length=64), server_default="America/Chicago", nullable=False)
    )
    op.add_column("webinars", sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("webinars", sa.Column("language", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webinars", "language")
    op.drop_column("webinars", "archived")
    op.drop_column("webinars", "timezone")
    # ### end Alembic commands ###
