"""news refactor

Revision ID: 74a15cde3921
Revises: 5ed5e36adc73
Create Date: 2026-08-16 18:36:26.191449

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "74a15cde3921"
down_revision: Union[str, None] = "5ed5e36adc73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news", sa.Column("title", sa.String(length=255), nullable=False))
    op.add_column("news", sa.Column("slug", sa.String(length=255), nullable=False))
    op.add_column("news", sa.Column("cover_key", sa.String(), nullable=True))
    op.create_index(op.f("ix_news_slug"), "news", ["slug"], unique=True)
    op.drop_column("news", "is_deleted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news",
        sa.Column("is_deleted", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_news_slug"), table_name="news")
    op.drop_column("news", "cover_key")
    op.drop_column("news", "slug")
    op.drop_column("news", "title")
    # ### end Alembic commands ###
