"""user profile information tables

Revision ID: 78a6c82b5bd6
Revises: ba5cfb79b5f5
Create Date: 2026-02-08 00:25:03.715802

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78a6c82b5bd6"
down_revision: Union[str, None] = "ba5cfb79b5f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_fellowship",
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("speciality", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_fellowship_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_fellowship")),
    )
    op.create_table(
        "users_professional_information",
        sa.Column("medical_school", sa.String(), nullable=False),
        sa.Column("medical_school_country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.Column("is_board_certified_pathologist", sa.Boolean(), nullable=False),
        sa.Column("is_us_pathology_trainee", sa.Boolean(), nullable=False),
        sa.Column("is_us_lab_professional", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_users_professional_information_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_professional_information")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_professional_information_user_id")),
    )
    op.create_table(
        "users_residency",
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("speciality", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("years_from_to", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_residency_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_residency")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_residency")
    op.drop_table("users_professional_information")
    op.drop_table("users_fellowship")
    # ### end Alembic commands ###
