"""deleted trained in the us

Revision ID: 854b7ea4d68e
Revises: 046b3ddb4455
Create Date: 2026-04-02 21:39:53.565537

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "854b7ea4d68e"
down_revision: Union[str, None] = "046b3ddb4455"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_memberships", "is_trained_in_us")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_memberships", sa.Column("is_trained_in_us", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
