"""postal code in user

Revision ID: 94c7026014d3
Revises: c95a7690cee6
Create Date: 2026-07-09 23:03:26.305780

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "94c7026014d3"
down_revision: Union[str, None] = "c95a7690cee6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("postal_code", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "postal_code")
    # ### end Alembic commands ###
