"""Job model, current_position field

Revision ID: 9700dc75fc2b
Revises: 1901826ca4d1
Create Date: 2026-03-18 18:31:06.830520

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9700dc75fc2b'
down_revision: Union[str, None] = '1901826ca4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_job',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_position', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('speciality', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('years_from_to', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_job_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_job'))
    )
    op.add_column('users_fellowship', sa.Column('current_position', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users_residency', sa.Column('current_position', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_residency', 'current_position')
    op.drop_column('users_fellowship', 'current_position')
    op.drop_table('users_job')
    # ### end Alembic commands ###
