"""deleted sponsorship requests

Revision ID: 002
Revises: 001
Create Date: 2026-01-19 00:18:49.488404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ae9dd6e12821"
down_revision = "2f846565bf54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sponsorship_requests")
    op.create_unique_constraint(op.f("uq_director_board_members_order"), "director_board_members", ["order"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_director_board_members_order"), "director_board_members", type_="unique")
    op.create_table(
        "sponsorship_requests",
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("company", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("_deleted", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsorship_requests")),
    )
    # ### end Alembic commands ###
