"""news when and where

Revision ID: af7689e668d1
Revises: b19c7e4a2d6f
Create Date: 2026-08-17 00:30:01.314412

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "af7689e668d1"
down_revision: Union[str, None] = "b19c7e4a2d6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news", sa.Column("when", sa.String(), nullable=True))
    op.add_column("news", sa.Column("where", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "where")
    op.drop_column("news", "when")
    # ### end Alembic commands ###
