"""add contact message replies

Revision ID: b9dc4ec67c04
Revises: ba5cfb79b5f5
Create Date: 2026-02-16 16:47:34.809615

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9dc4ec67c04"
down_revision: Union[str, None] = "ba5cfb79b5f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_message_replies",
        sa.Column("contact_message_id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_message_id"],
            ["contact_messages.id"],
            name=op.f("fk_contact_message_replies_contact_message_id_contact_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_message_replies")),
    )
    op.create_index(
        op.f("ix_contact_message_replies_contact_message_id"),
        "contact_message_replies",
        ["contact_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contact_message_replies_contact_message_id"), table_name="contact_message_replies")
    op.drop_table("contact_message_replies")
    # ### end Alembic commands ###
