"""case of the month permissions

Revision ID: bccf1fc16e0d
Revises: 4d0f674b8e59
Create Date: 2026-10-02 22:44:52.037740

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bccf1fc16e0d"
down_revision: Union[str, None] = "4d0f674b8e59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    metadata = sa.MetaData()
    bind = op.get_bind()

    permissions_table = sa.Table(
        "permissions",
        metadata,
        autoload_with=bind,
    )

    op.bulk_insert(
        permissions_table,
        [
            {"action": "case_of_the_month.create", "name": "Create case of the month"},
            {"action": "case_of_the_month.view", "name": "View case of the month"},
            {"action": "case_of_the_month.delete", "name": "Delete case of the month"},
            {"action": "case_of_the_month.update", "name": "Update case of the month"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM permissions WHERE action IN (
            'case_of_the_month.create',
            'case_of_the_month.view',
            'case_of_the_month.delete',
            'case_of_the_month.update'
        )
    """)
    # ### end Alembic commands ###
