"""webinars

Revision ID: c765f7c52e5c
Revises: 6de1b0ef7687
Create Date: 2026-08-01 20:59:55.067015

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c765f7c52e5c"
down_revision: Union[str, None] = "6de1b0ef7687"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webinars",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("learning_objectives", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("speaker_name", sa.String(), nullable=False),
        sa.Column("speaker_description", sa.String(), nullable=True),
        sa.Column("registration_link", sa.Text(), nullable=True),
        sa.Column("join_link", sa.Text(), nullable=True),
        sa.Column("recording_link", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("member_only", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webinars")),
    )
    op.create_index(op.f("ix_webinars_slug"), "webinars", ["slug"], unique=True)
    op.create_index(op.f("ix_webinars_starts_at"), "webinars", ["starts_at"], unique=False)
    op.create_table(
        "webinars_registered_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("webinar_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_webinars_registered_users_user_id_users")),
        sa.ForeignKeyConstraint(
            ["webinar_id"], ["webinars.id"], name=op.f("fk_webinars_registered_users_webinar_id_webinars")
        ),
        sa.PrimaryKeyConstraint("user_id", "webinar_id", name=op.f("pk_webinars_registered_users")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webinars_registered_users")
    op.drop_index(op.f("ix_webinars_starts_at"), table_name="webinars")
    op.drop_index(op.f("ix_webinars_slug"), table_name="webinars")
    op.drop_table("webinars")
    # ### end Alembic commands ###
