"""active member to full

Revision ID: c95a7690cee6
Revises: 38c9fd543cde
Create Date: 2026-06-24 21:33:00.653250

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c95a7690cee6"
down_revision: Union[str, None] = "38c9fd543cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE membership_types SET name = 'Full Member' WHERE name = 'Active Member'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE membership_types SET name = 'Active Member' WHERE name = 'Full Member'
    """)
    # ### end Alembic commands ###
