"""extended contact messages

Revision ID: 003
Revises: 002
Create Date: 2026-01-19 01:04:51.431046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d40a344e3cf9"
down_revision = "ae9dd6e12821"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contact_messages", sa.Column("contact_message", sa.Text(), nullable=True))
    op.add_column("contact_messages", sa.Column("role_affiliation", sa.String(length=256), nullable=True))
    op.add_column("contact_messages", sa.Column("get_involved_message", sa.Text(), nullable=True))
    op.alter_column("contact_messages", "subject", existing_type=sa.VARCHAR(length=256), nullable=True)
    op.drop_column("contact_messages", "message")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contact_messages", sa.Column("message", sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.alter_column("contact_messages", "subject", existing_type=sa.VARCHAR(length=256), nullable=False)
    op.drop_column("contact_messages", "get_involved_message")
    op.drop_column("contact_messages", "role_affiliation")
    op.drop_column("contact_messages", "contact_message")
    # ### end Alembic commands ###
