"""nullable professional info

Revision ID: d6de1a40ad1f
Revises: ae959c5011a7
Create Date: 2026-04-15 20:42:22.037256

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6de1a40ad1f"
down_revision: Union[str, None] = "ae959c5011a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "institution", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "institution", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
