"""Initial

Revision ID: 000
Revises:
Create Date: 2025-12-25 22:58:13.469295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from passlib.handlers.bcrypt import bcrypt
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
from app.core.config import DEV_MODE

revision = "d9064d4df926"
down_revision = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_messages",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.Column("answered", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_messages")),
    )
    membership_types_table = op.create_table(
        "membership_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ACTIVE", "TRAINEE", "AFFILIATE", "HONORARY", "PATHWAY", name="membership_type_enum"),
            nullable=False,
        ),
        sa.Column("price_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_purchasable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_types")),
    )
    permissions_table = op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
    )
    op.create_table(
        "sponsorship_requests",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("company", sa.String(length=256), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsorship_requests")),
    )
    users_table = op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("stuff", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("pending", sa.Boolean(), server_default=sa.text("true"), nullable=True),
        sa.Column("institution", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("last_password_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_confirmed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("_password", sa.String(), nullable=False),
        sa.Column("avatar_path", sa.String(), nullable=True),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("avatar_path", name=op.f("uq_users_avatar_path")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_users_phone_number")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "news",
        sa.Column("body", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("is_published", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_news_author_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news")),
    )
    op.create_table(
        "users_memberships",
        sa.Column(
            "approval_status",
            sa.Enum("APPROVED", "PENDING", "REJECTED", name="approval_status_enum"),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("has_access", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("membership_type_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_users_memberships_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_memberships_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_memberships")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_memberships_user_id")),
    )
    op.create_table(
        "users_permissions",
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], name=op.f("fk_users_permissions_permission_id_permissions")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_permissions_user_id_users")),
        sa.PrimaryKeyConstraint("permission_id", "user_id", name=op.f("pk_users_permissions")),
    )
    # ### end Alembic commands ###

    if DEV_MODE:
        hashed_password = bcrypt.hash("admin")
        op.bulk_insert(
            users_table,
            [
                {
                    "firstname": "Admin",
                    "lastname": "User",
                    "email": "admin@mail.com",
                    "stuff": True,
                    "description": "Development superuser",
                    "institution": "Dev Institution",
                    "role": "admin",
                    "_password": hashed_password,
                    "pending": False,
                }
            ],
        )

    op.bulk_insert(
        membership_types_table,
        [
            {
                "name": "Active Member",
                "type": "ACTIVE",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Any legally qualified Russian-speaking specialist (MD, DO, MBBS, PhD, or equivalent degree). practicing pathology in the united states",
                "is_purchasable": True,
            },
            {
                "name": "Trainee Member",
                "type": "TRAINEE",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Russian-speaking residents or fellows in pathology or related disciplines in the United States.",
                "is_purchasable": True,
            },
            {
                "name": "Affiliate Member",
                "type": "AFFILIATE",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Russian-speaking pathologists, scientists, researchers, or allied professionals interested in the field of pathology whose involvement is relevant and contributes meaningfully to the Society (non-voting).",
                "is_purchasable": True,
            },
            {
                "name": "Honorary Member",
                "type": "HONORARY",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Individuals recognized fo exceptional service to the field of pathology or the Society (non-voting).",
                "is_purchasable": False,
            },
            {
                "name": "Pathway Member",
                "type": "PATHWAY",
                "price_usd": 20.00,
                "duration": 365,
                "description": "Russian-speaking individuals pursuing or transition into a medical career in the United States. This includes medical students and internationally trained medical graduates seeking mentorship and professional development as they prepare for pathology practice in the United States (non-voting).",
                "is_purchasable": True,
            },
        ],
    )

    op.bulk_insert(
        permissions_table,
        [
            # admin permissions
            {"action": "admin.create", "name": "Assign admin role"},
            {"action": "admin.view", "name": "View admin profile"},
            {"action": "admin.delete", "name": "Remove admin role"},
            {"action": "admin.update", "name": "Update admin profile"},
            # permission permissions
            {"action": "permissions.create", "name": "Create permissions"},
            {"action": "permissions.view", "name": "Read permissions"},
            {"action": "permissions.delete", "name": "Delete permissions"},
            {"action": "permissions.update", "name": "Update permissions"},
            # memberships permissions
            {"action": "memberships.create", "name": "Create memberships"},
            {"action": "memberships.view", "name": "Read memberships"},
            {"action": "memberships.delete", "name": "Delete memberships"},
            {"action": "memberships.update", "name": "Update memberships"},
            # user memberships permissions
            {"action": "user_memberships.create", "name": "Create users memberships"},
            {"action": "user_memberships.view", "name": "Read users memberships"},
            {"action": "user_memberships.delete", "name": "Delete users memberships"},
            {"action": "user_memberships.update", "name": "Update users memberships"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_permissions")
    op.drop_table("users_memberships")
    op.drop_table("news")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("sponsorship_requests")
    op.drop_table("permissions")
    op.drop_table("membership_types")
    op.drop_table("contact_messages")
    # ### end Alembic commands ###
    # ### drop enums explicitly ###
    op.execute("DROP TYPE IF EXISTS approval_status_enum")
    op.execute("DROP TYPE IF EXISTS membership_type_enum")
