"""add preferred_name to users

Revision ID: e25423541c91
Revises: 046b3ddb4455
Create Date: 2026-03-31 00:55:51.479211

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e25423541c91'
down_revision: Union[str, None] = '046b3ddb4455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_name')
    # ### end Alembic commands ###
