"""add_superuser_to_user

Revision ID: ea0d3a55a959
Revises: c0560a10ef3c
Create Date: 2026-06-03 16:09:16.761778

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea0d3a55a959"
down_revision: Union[str, None] = "c0560a10ef3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("superuser", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.execute("UPDATE users SET superuser = true WHERE email = 'admin@mail.com'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "superuser")
    # ### end Alembic commands ###
