"""add communication preferences table

Revision ID: f40e24e4429d
Revises: 78a6c82b5bd6
Create Date: 2026-02-22 16:15:58.989562

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f40e24e4429d'
down_revision: Union[str, None] = '78a6c82b5bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_communication_preferences',
    sa.Column('membership_account_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('newsletters', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('events_meetings', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('committees_leadership', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('volunteer_opportunities', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_communication_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_communication_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_users_communication_preferences_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_communication_preferences')
    # ### end Alembic commands ###
