"""username change model

Revision ID: f9780a34a084
Revises: ec60ae60d61d
Create Date: 2026-02-20 15:22:01.054046

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9780a34a084'
down_revision: Union[str, None] = 'ec60ae60d61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('reason_change', sa.String(), nullable=False),
    sa.Column('reason_rejecting', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'APPROVED', 'REJECTED', name='user_name_change_status_enum'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_username_changes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_username_changes'))
    )
    op.add_column('users', sa.Column('last_name_change', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name_change')
    op.drop_table('username_changes')
    # ### end Alembic commands ###
