"""refactor UserMembership to MembershipRequest

Revision ID: f9a34e2d51c1
Revises: 854b7ea4d68e
Create Date: 2026-04-04 11:36:11.328623

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9a34e2d51c1"
down_revision: Union[str, None] = "854b7ea4d68e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "membership_requests",
        sa.Column(
            "status",
            sa.Enum(
                "PAYMENT_PENDING",
                "PAID",
                "APPROVED",
                "REJECTED",
                "PAYMENT_FAILED",
                name="membership_request_status_enum",
            ),
            server_default=sa.text("'PAYMENT_PENDING'"),
            nullable=False,
        ),
        sa.Column("primary_affiliation", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.Column("practice_setting", sa.String(), nullable=False),
        sa.Column("subspecialty", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_comment", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("membership_type_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_membership_requests_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_membership_requests_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_requests")),
        sa.UniqueConstraint("user_id", name=op.f("uq_membership_requests_user_id")),
    )
    op.drop_table("users_memberships")
    op.execute("DROP TYPE IF EXISTS approval_status_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_memberships",
        sa.Column(
            "approval_status",
            postgresql.ENUM("APPROVED", "PENDING", "REJECTED", name="approval_status_enum"),
            server_default=sa.text("'PENDING'::approval_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("current_period_end", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("membership_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("_deleted", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("primary_affiliation", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("job_title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("practice_setting", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subspecialty", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("auto_renewal", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_users_memberships_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_memberships_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_memberships")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("uq_users_memberships_user_id"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("membership_requests")
    op.execute("DROP TYPE IF EXISTS membership_request_status_enum")
    # ### end Alembic commands ###
