"""user membership

Revision ID: fac5c394e2c1
Revises: 4f7c67fabbd9
Create Date: 2026-05-02 23:11:55.611003

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fac5c394e2c1"
down_revision: Union[str, None] = "4f7c67fabbd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_memberships",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("membership_request_id", sa.Integer(), nullable=False),
        sa.Column("membership_type_id", sa.Integer(), nullable=False),
        sa.Column("_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["membership_request_id"],
            ["membership_requests.id"],
            name=op.f("fk_users_memberships_membership_request_id_membership_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["membership_type_id"],
            ["membership_types.id"],
            name=op.f("fk_users_memberships_membership_type_id_membership_types"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_users_memberships_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_memberships")),
        sa.UniqueConstraint("membership_request_id", name=op.f("uq_users_memberships_membership_request_id")),
        sa.UniqueConstraint("user_id", name=op.f("uq_users_memberships_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_memberships")
    # ### end Alembic commands ###
