"""implement_membership_access_and_refactor_usermembership

Revision ID: ffff45a3f270
Revises: 1901826ca4d1
Create Date: 2026-03-04 10:44:11.750024

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffff45a3f270"
down_revision: Union[str, None] = "1901826ca4d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_memberships",
        sa.Column("auto_renewal", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.drop_column("users_memberships", "cancel_at_period_end")
    op.drop_column("users_memberships", "has_access")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_memberships",
        sa.Column("has_access", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute(
        """
        UPDATE users_memberships
        SET has_access = CASE
            WHEN approval_status != 'APPROVED' THEN false
            WHEN current_period_end IS NULL THEN true
            WHEN current_period_end > NOW() THEN true
            ELSE false
        END
        """
    )
    op.alter_column("users_memberships", "has_access", nullable=False)
    op.add_column(
        "users_memberships",
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.drop_column("users_memberships", "auto_renewal")
    # ### end Alembic commands ###
