"""implement_membership_access_and_refactor_usermembership

Revision ID: ffff45a3f270
Revises: 1901826ca4d1
Create Date: 2026-03-04 10:44:11.750024

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ffff45a3f270'
down_revision: Union[str, None] = '1901826ca4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Check for existing columns to ensure idempotency
    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name = 'membership_types';"))
    mt_cols = [row[0] for row in res]

    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name = 'users_memberships';"))
    um_cols = [row[0] for row in res]

    if 'type' not in mt_cols:
        op.add_column('membership_types', sa.Column('type', sa.Enum('ACTIVE', 'TRAINEE', 'AFFILIATE', 'HONORARY', 'PATHWAY', name='membership_type_enum'), nullable=False, server_default='ACTIVE'))
    if 'price_usd' not in mt_cols:
        op.add_column('membership_types', sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'))
    if 'duration' not in mt_cols:
        op.add_column('membership_types', sa.Column('duration', sa.Integer(), nullable=False, server_default='365'))
    if 'description' not in mt_cols:
        op.add_column('membership_types', sa.Column('description', sa.String(), nullable=True))
    if 'is_purchasable' not in mt_cols:
        op.add_column('membership_types', sa.Column('is_purchasable', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    if 'cancel_at_period_end' not in um_cols:
        op.add_column('users_memberships', sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    if 'auto_renewal' not in um_cols:
        op.add_column('users_memberships', sa.Column('auto_renewal', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    if 'has_access' in um_cols:
        op.drop_column('users_memberships', 'has_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name = 'membership_types';"))
    mt_cols = [row[0] for row in res]

    res = conn.execute(sa.text("SELECT column_name FROM information_schema.columns WHERE table_name = 'users_memberships';"))
    um_cols = [row[0] for row in res]

    if 'has_access' not in um_cols:
        op.add_column('users_memberships', sa.Column('has_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    if 'auto_renewal' in um_cols:
        op.drop_column('users_memberships', 'auto_renewal')
    if 'cancel_at_period_end' in um_cols:
        op.drop_column('users_memberships', 'cancel_at_period_end')
    if 'is_purchasable' in mt_cols:
        op.drop_column('membership_types', 'is_purchasable')
    if 'description' in mt_cols:
        op.drop_column('membership_types', 'description')
    if 'duration' in mt_cols:
        op.drop_column('membership_types', 'duration')
    if 'price_usd' in mt_cols:
        op.drop_column('membership_types', 'price_usd')
    if 'type' in mt_cols:
        op.drop_column('membership_types', 'type')

    op.execute("DROP TYPE IF EXISTS membership_type_enum")
    # ### end Alembic commands ###
